# Cloudflare Pages configuration
name = "stockpilot"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

# Environment variables
[env.production]
# Production environment variables go here
# Example:
# VITE_FIREBASE_PROJECT_ID = "your-firebase-project-id"

[env.preview]
# Preview environment variables go here

# Triggers for scheduled tasks
[triggers]
crons = []  # Add any schedule triggers if needed
